/*
-- Query: SELECT * FROM mc536.MusicalArtist
LIMIT 0, 1000

-- Date: 2014-05-16 21:57
*/
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (1,'Acid Black Cherry',NULL,NULL,'2007-02-00','http://en.wikipedia.org/wiki/Acid_Black_Cherry');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (2,'Gorillaz',NULL,NULL,'1998-02-00','http://en.wikipedia.org/wiki/Gorillaz');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (3,'Nightmare',NULL,NULL,'2000-02-00','http://en.wikipedia.org/wiki/Nightmare_(Japanese_band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (4,'Orange Range',NULL,NULL,'2001-02-00','http://en.wikipedia.org/wiki/Orange_Range');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (5,'Paul McCartney',NULL,NULL,'1957-02-00','http://en.wikipedia.org/wiki/Paul_McCartney');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (6,'Queen',NULL,NULL,'1970-02-00','http://en.wikipedia.org/wiki/Queen_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (7,'Sound Horizon',NULL,NULL,'2001-02-00','http://en.wikipedia.org/wiki/Sound_Horizon');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (9,'Arctic Monkeys',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Arctic_monkeys');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (10,'Imagine Dragons',NULL,NULL,'2007-02-00','http://en.wikipedia.org/wiki/Imagine_Dragons');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (11,'Los Hermanos',NULL,27,'1997-02-00','http://en.wikipedia.org/wiki/Los_Hermanos');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (12,'Muse',NULL,136,'1994-02-00','http://en.wikipedia.org/wiki/Muse_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (13,'Nine Inch Nails',NULL,93,'1988-02-00','http://en.wikipedia.org/wiki/Nine_inch_nails');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (14,'Nirvana',NULL,35,'1987-02-00','http://en.wikipedia.org/wiki/Nirvana_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (15,'Placebo',NULL,10,'1994-02-00','http://en.wikipedia.org/wiki/Placebo_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (16,'Queens of the Stone Age',NULL,124,'1996-02-00','http://en.wikipedia.org/wiki/Queens_of_the_stone_age');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (17,'Radiohead',NULL,117,'1985-02-00','http://en.wikipedia.org/wiki/Radiohead');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (18,'The Black Keys',NULL,91,'2001-02-00','http://en.wikipedia.org/wiki/The_Black_Keys');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (19,'The Kooks',NULL,60,'2002-02-00','http://en.wikipedia.org/wiki/The_Kooks');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (20,'The Strokes',NULL,NULL,'1998-02-00','http://en.wikipedia.org/wiki/The_Strokes');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (21,'Apink',NULL,156,'2011-02-00','http://en.wikipedia.org/wiki/A_Pink');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (22,'Claudia Leitte',NULL,28,'2001-02-00','http://en.wikipedia.org/wiki/Claudia_Leitte');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (23,'deadmau5',NULL,103,'2005-02-00','http://en.wikipedia.org/wiki/Deadmau5');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (24,'Eminem',NULL,NULL,'1990-02-00','http://en.wikipedia.org/wiki/Eminem');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (25,'Linkin Park',NULL,NULL,'1996-02-00','http://en.wikipedia.org/wiki/Linkin_Park');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (26,'Two Steps From Hell',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Two_Steps_From_Hell');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (27,'Yousei Teikoku',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Yousei_Teikoku');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (28,'Zedd',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Zedd_(musician)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (30,'Helloween',NULL,129,'1984-02-00','http://en.wikipedia.org/wiki/Helloween');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (31,'Iron Maiden',NULL,11,'1975-02-00','http://en.wikipedia.org/wiki/Iron_Maiden');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (32,'Karnivool',NULL,12,'1997-02-00','http://en.wikipedia.org/wiki/Karnivool');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (33,'Metallica',NULL,NULL,'1981-02-00','http://en.wikipedia.org/wiki/Metallica');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (34,'Pain of Salvation',NULL,144,'1984-02-00','http://en.wikipedia.org/wiki/Pain_of_Salvation');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (35,'Paramore',NULL,NULL,'2004-02-00','http://en.wikipedia.org/wiki/Paramore');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (36,'Protest the Hero',NULL,145,'2001-02-00','http://en.wikipedia.org/wiki/Protest_the_Hero');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (37,'Tesseract',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Tesseract');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (38,'The Safety Fire',NULL,10,'2006-02-00','http://en.wikipedia.org/wiki/The_Safety_Fire');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (39,'Aerosmith',NULL,74,'1970-02-00','http://en.wikipedia.org/wiki/Aerosmith');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (81,'Audioslave',NULL,NULL,'2001-02-00','http://en.wikipedia.org/wiki/Audioslave');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (82,'Avicii',NULL,115,'2007-02-00','http://en.wikipedia.org/wiki/Avicii');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (83,'Bon Jovi',NULL,NULL,'1983-02-00','http://en.wikipedia.org/wiki/Bon_jovi');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (84,'Chris Cornell',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Chris_cornell');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (85,'Daft Punk',NULL,21,'1993-02-00','http://en.wikipedia.org/wiki/Daft_punk');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (86,'Eric Clapton',NULL,NULL,'1962-02-00','http://en.wikipedia.org/wiki/Eric_clapton');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (87,'Florence and the Machine',NULL,10,'2007-02-00','http://en.wikipedia.org/wiki/Florence_and_the_Machine');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (88,'Hardwell',NULL,NULL,'2006-02-00','http://en.wikipedia.org/wiki/Hardwell');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (90,'Kara\'s Flowers',NULL,15,'1994-02-00','http://en.wikipedia.org/wiki/Maroon_5');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (91,'Matchbox 20',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Matchbox_20');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (93,'Nickelback',NULL,62,'1995-02-00','http://en.wikipedia.org/wiki/Nickelback');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (95,'Oasis',NULL,NULL,'1991-02-00','http://en.wikipedia.org/wiki/Oasis_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (96,'Pink Floyd',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Pink_Floyd');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (97,'Red Hot Chili Peppers',NULL,15,'1983-02-00','http://en.wikipedia.org/wiki/Red_Hot_Chili_Peppers');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (98,'The Offspring',NULL,NULL,'1984-02-00','http://en.wikipedia.org/wiki/The_Offspring');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (100,'Alanis Morissette',NULL,111,'1987-02-00','http://en.wikipedia.org/wiki/Alanis_Morissette');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (101,'Britney Spears',NULL,NULL,'1992-02-00','http://en.wikipedia.org/wiki/Britney_Spears');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (102,'Céu',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/C%C3%A9u');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (103,'Clarice Falcão',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Clarice_Falc%C3%A3o');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (104,'Fernando e Sorocaba',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Fernando_e_Sorocaba');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (109,'O Rappa',NULL,27,'1993-02-00','http://en.wikipedia.org/wiki/O_Rappa');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (110,'Shakira',NULL,NULL,'1990-02-00','http://en.wikipedia.org/wiki/Shakira');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (111,'Alice in Chains',NULL,39,'1987-02-00','http://en.wikipedia.org/wiki/Alice_in_Chains');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (112,'Bad Company',NULL,NULL,'1973-02-00','http://en.wikipedia.org/wiki/Bad_Company');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (113,'Badlands',NULL,15,'1988-02-00','http://en.wikipedia.org/wiki/Badlands_(American_band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (115,'Explosions in the Sky',NULL,107,'1999-02-00','http://en.wikipedia.org/wiki/Explosions_in_the_Sky');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (120,'Serafin',NULL,NULL,'2000-02-00','http://en.wikipedia.org/wiki/Serafin_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (121,'Soundgarden',NULL,NULL,'1984-02-00','http://en.wikipedia.org/wiki/Soundgarden');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (122,'Stone Temple Pilots',NULL,43,'1986-02-00','http://en.wikipedia.org/wiki/Stone_Temple_Pilots');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (124,'Third Eye Blind',NULL,105,'1993-02-00','http://en.wikipedia.org/wiki/Third_Eye_Blind');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (125,'Tool',NULL,NULL,'1990-02-00','http://en.wikipedia.org/wiki/Tool_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (126,'Velvet Revolver',NULL,55,'2002-02-00','http://en.wikipedia.org/wiki/Velvet_Revolver');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (127,'3 Doors Down',NULL,42,'1996-02-00','http://en.wikipedia.org/wiki/3_Doors_Down');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (130,'Black Sabbath',NULL,NULL,'1968-02-00','http://en.wikipedia.org/wiki/Black_Sabbath');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (131,'Capital Inicial',NULL,87,'1982-02-00','http://en.wikipedia.org/wiki/Capital_Inicial');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (132,'Coldplay',NULL,10,'1996-02-00','http://en.wikipedia.org/wiki/Coldplay');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (133,'Creed',NULL,126,'1994-02-00','http://en.wikipedia.org/wiki/Creed_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (134,'Foo Fighters',NULL,39,'1994-02-00','http://en.wikipedia.org/wiki/Foo_Fighters');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (135,'Goo Goo Dolls',NULL,153,'1986-02-00','http://en.wikipedia.org/wiki/Goo_Goo_Dolls');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (137,'Ira',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Ira_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (139,'Kansas',NULL,17,'1973-02-00','http://en.wikipedia.org/wiki/Kansas_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (140,'Kiss',NULL,NULL,'1973-02-00','http://en.wikipedia.org/wiki/Kiss_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (141,'Led Zeppelin',NULL,NULL,'1968-02-00','http://en.wikipedia.org/wiki/Led_Zeppelin');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (144,'Living Colour',NULL,NULL,'1984-02-00','http://en.wikipedia.org/wiki/Living_Colour');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (145,'Mamonas Assassinas',NULL,84,'1994-02-00','http://en.wikipedia.org/wiki/Mamonas_Assassinas');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (150,'Ozzy Osbourne',NULL,NULL,'1967-02-00','http://en.wikipedia.org/wiki/Ozzy_Osbourne');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (151,'Pearl Jam',NULL,39,'1990-02-00','http://en.wikipedia.org/wiki/Pearl_Jam');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (154,'Rage Against The Machine',NULL,15,'1991-02-00','http://en.wikipedia.org/wiki/Rage_Against_the_Machine');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (155,'Raul Seixas',NULL,NULL,'1963-02-00','http://en.wikipedia.org/wiki/Raul_Seixas');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (158,'Sex Pistols',NULL,NULL,'1975-02-00','http://en.wikipedia.org/wiki/Sex_pistols');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (159,'Skid Row',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Skid_row');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (160,'The Calling',NULL,15,'2000-02-00','http://en.wikipedia.org/wiki/The_Calling');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (161,'The Killers',NULL,NULL,'2001-02-00','http://en.wikipedia.org/wiki/The_Killers');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (163,'The Rolling Stones',NULL,10,'1962-02-00','http://en.wikipedia.org/wiki/The_Rolling_Stones');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (164,'The White Stripes',NULL,141,'1997-02-00','http://en.wikipedia.org/wiki/The_White_Stripes');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (165,'The Police',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/The_police');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (166,'Thin Lizzy',NULL,44,'1969-02-00','http://en.wikipedia.org/wiki/Thin_Lizzy');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (168,'Twisted Sister',NULL,36,'1972-02-00','http://en.wikipedia.org/wiki/Twisted_Sister');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (169,'U2',NULL,44,'1976-02-00','http://en.wikipedia.org/wiki/U2');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (170,'Van Halen',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Van_halen');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (171,'Whitesnake',NULL,NULL,'1978-02-00','http://en.wikipedia.org/wiki/Whitesnake');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (172,'Yes',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Yes_band');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (176,'Avantasia',NULL,NULL,'1999-02-00','http://en.wikipedia.org/wiki/Avantasia');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (177,'Beatles',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Beatles');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (178,'Blind Guardian',NULL,61,'1984-02-00','http://en.wikipedia.org/wiki/Blind_guardian');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (180,'Dream Theater',NULL,74,'1985-02-00','http://en.wikipedia.org/wiki/Dream_Theater');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (181,'Eddie Van Halen',NULL,NULL,'1972-02-00','http://en.wikipedia.org/wiki/Eddie_Van_Halen');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (182,'Edguy',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Edguy');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (184,'Foster the People',NULL,NULL,'2009-02-00','http://en.wikipedia.org/wiki/The_foo_fighters');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (189,'Mortorhead',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Motorhead');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (192,'Ramones',NULL,69,'1974-02-00','http://en.wikipedia.org/wiki/Ramones');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (194,'Sonata Arctica',NULL,NULL,'1995-02-00','http://en.wikipedia.org/wiki/Sonata_Arctica');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (195,'The Doors',NULL,15,'1965-02-00','http://en.wikipedia.org/wiki/The_doors');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (198,'Armin van Buuren',NULL,52,'1995-02-00','http://en.wikipedia.org/wiki/Armin_van_buuren');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (200,'Charlie Brown Jr.',NULL,31,'1992-02-00','http://en.wikipedia.org/wiki/Charlie_Brown_Jr.');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (205,'X Japan',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/X_japan');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (206,'Yui',NULL,NULL,'2004-02-00','http://en.wikipedia.org/wiki/Yui_(singer)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (209,'Arcade Fire',NULL,57,'2001-02-00','http://en.wikipedia.org/wiki/Arcade_Fire');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (211,'Bad Brains',NULL,NULL,'1977-02-00','http://en.wikipedia.org/wiki/Bad_Brains');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (212,'Black Drawing Chalks',NULL,54,'2005-02-00','http://en.wikipedia.org/wiki/Black_Drawing_Chalks');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (213,'Black Flag',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Black_Flag');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (214,'Black Label Society',NULL,15,'1998-02-00','http://en.wikipedia.org/wiki/Black_Label_Society');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (217,'Death',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Death');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (218,'Down',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Down');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (219,'Exodus',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Exodus');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (220,'Hatebreed',NULL,2,'1994-02-00','http://en.wikipedia.org/wiki/Hatebreed');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (221,'Iced Earth',NULL,16,'1985-02-00','http://en.wikipedia.org/wiki/Iced_Earth');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (222,'James Marshall Hendrix',NULL,NULL,'1963-02-00','http://en.wikipedia.org/wiki/Jimi_Hendrix');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (223,'Kreator',NULL,NULL,'1982-02-00','http://en.wikipedia.org/wiki/Kreator');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (224,'Krisiun',NULL,90,'1990-02-00','http://en.wikipedia.org/wiki/Krisiun');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (226,'Lynyrd Skynyrd',NULL,85,'1964-02-00','http://en.wikipedia.org/wiki/Lynyrd_Skynyrd');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (227,'Macaco Bong',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Macaco_Bong');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (228,'Miles Dewey Davis III Davis',NULL,NULL,'1944-02-00','http://en.wikipedia.org/wiki/Miles_Davis');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (229,'Minor Threat',NULL,100,'1980-02-00','http://en.wikipedia.org/wiki/Minor_Threat');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (231,'Pantera',NULL,NULL,'1981-02-00','http://en.wikipedia.org/wiki/Pantera');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (234,'Slayer',NULL,NULL,'1981-02-00','http://en.wikipedia.org/wiki/Slayer');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (235,'Tame Impala',NULL,12,'2007-02-00','http://en.wikipedia.org/wiki/Tame_Impala');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (236,'The Allman Brothers Band',NULL,99,'1969-02-00','http://en.wikipedia.org/wiki/The_Allman_Brothers_Band');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (237,'The Misfits',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/The_Misfits');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (238,'The National',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/The_National');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (239,'Bruno e Marrone',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Bruno_e_Marrone');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (240,'Chitãozinho e Xororó',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Chit%C3%A3ozinho_e_Xoror%C3%B3');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (241,'Elvis Aaron Presley',NULL,NULL,'1953-02-00','http://en.wikipedia.org/wiki/Elvis_Presley');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (243,'Gusttavo Lima',NULL,NULL,'2009-02-00','http://en.wikipedia.org/wiki/Gusttavo_Lima');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (244,'Jorge e Mateus',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Jorge_e_Mateus');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (245,'Leandro e Leonardo',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Leandro_e_Leonardo');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (246,'Legião Urbana',NULL,87,'1982-02-00','http://en.wikipedia.org/wiki/Legi%C3%A3o_Urbana');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (247,'Luan Santana',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Luan_Santana');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (248,'Lulu Santos',NULL,NULL,'1972-02-00','http://en.wikipedia.org/wiki/Lulu_Santos');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (250,'Roberto Carlos',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Roberto_Carlos');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (251,'Roupa Nova',NULL,28,'1980-02-00','http://en.wikipedia.org/wiki/Roupa_Nova');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (252,'Só Pra Contrariar',NULL,19,'1989-02-00','http://en.wikipedia.org/wiki/S%C3%B3_Pra_Contrariar');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (253,'Skank',NULL,8,'1991-02-00','http://en.wikipedia.org/wiki/Skank_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (254,'Titãs',NULL,30,'1981-02-00','http://en.wikipedia.org/wiki/Tit%C3%A3s');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (255,'Tribalistas',NULL,NULL,'2002-02-00','http://en.wikipedia.org/wiki/Tribalistas_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (256,'Zezé de Camargo e Luciano',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Zez%C3%A9_Di_Camargo_%26_Luciano');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (258,'Godsmack',NULL,NULL,'1995-02-00','http://en.wikipedia.org/wiki/Godsmack');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (259,'Matanza',NULL,27,'1996-02-00','http://en.wikipedia.org/wiki/Matanza_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (262,'Sepultura',NULL,3,'1984-02-00','http://en.wikipedia.org/wiki/Sepultura');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (264,'Suicidal Tendencies',NULL,NULL,'1981-02-00','http://en.wikipedia.org/wiki/Suicidal_Tendencies');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (267,'Coldplay',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Cold_play');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (268,'Deep Purple',NULL,157,'1968-02-00','http://en.wikipedia.org/wiki/Deep_Purple');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (269,'Enya',NULL,NULL,'1982-02-00','http://en.wikipedia.org/wiki/Enya');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (278,'Nando Reis',NULL,NULL,'1984-02-00','http://en.wikipedia.org/wiki/Nando_Reis');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (279,'Paulo Vanzolini',NULL,NULL,'1942-02-00','http://en.wikipedia.org/wiki/Paulo_Vanzolini');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (281,'Tom Jobim',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Tom_Jobin');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (283,'Banda Calypso',NULL,82,'1999-02-00','http://en.wikipedia.org/wiki/Banda_Calypso');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (285,'Engenheiros do Hawaii',NULL,46,'1985-02-00','http://en.wikipedia.org/wiki/Engenheiros_do_Hawaii');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (286,'Evanescence',NULL,94,'1995-02-00','http://en.wikipedia.org/wiki/Evanescence');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (290,'Jonas Brothers',NULL,NULL,'2005-02-00','http://en.wikipedia.org/wiki/Jonas_Brothers');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (294,'Nightwish',NULL,NULL,'1996-02-00','http://en.wikipedia.org/wiki/Nightwish');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (298,'3OH!3',NULL,NULL,'2004-02-00','http://en.wikipedia.org/wiki/3OH!3');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (299,'50 cent',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/50_cent');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (300,'ABBA',NULL,115,'1972-02-00','http://en.wikipedia.org/wiki/ABBA');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (301,'AFI',NULL,147,'1991-02-00','http://en.wikipedia.org/wiki/AFI_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (302,'Avril Lavigne',NULL,NULL,'1999-02-00','http://en.wikipedia.org/wiki/Avril_Lavigne');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (303,'Backstreet Boys',NULL,22,'1993-02-00','http://en.wikipedia.org/wiki/Backstreet_boys');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (309,'Crystal Castles',NULL,103,'2004-02-00','http://en.wikipedia.org/wiki/Crystal_Castles_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (310,'Sir Elton John',NULL,NULL,'1964-02-00','http://en.wikipedia.org/wiki/Elton_John');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (313,'Fall Out Boy',NULL,121,'2001-02-00','http://en.wikipedia.org/wiki/Fall_Out_Boy');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (315,'Jennifer Lopez',NULL,NULL,'1986-02-00','http://en.wikipedia.org/wiki/Jennifer_Lopez');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (316,'Kesha Rose Sebert',NULL,NULL,'2005-02-00','http://en.wikipedia.org/wiki/Kesha');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (318,'Lady Gaga',NULL,NULL,'2005-02-00','http://en.wikipedia.org/wiki/Lady_Gaga');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (320,'Madonna',NULL,NULL,'1979-02-00','http://en.wikipedia.org/wiki/Madonna_(entertainer)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (323,'Miley Cyrus',NULL,NULL,'2001-02-00','http://en.wikipedia.org/wiki/Miley_cyrus');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (325,'Panic! at the Disco',NULL,45,'2004-02-00','http://en.wikipedia.org/wiki/Panic!_at_the_Disco');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (327,'Phoenix',NULL,128,'1999-02-00','http://en.wikipedia.org/wiki/Phoenix_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (328,'Plain White T\'s',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Plain_White_T%27s');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (329,'Rihanna',NULL,NULL,'2004-02-00','http://en.wikipedia.org/wiki/Rihanna');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (330,'Saosin',NULL,37,'2003-02-00','http://en.wikipedia.org/wiki/Saosin');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (331,'Spice Girls',NULL,10,'1994-02-00','http://en.wikipedia.org/wiki/Spice_girls');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (332,'Sum 41',NULL,148,'1996-02-00','http://en.wikipedia.org/wiki/Sum_41');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (333,'T.a.t.u',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/T.a.t.u.');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (336,'The Smiths',NULL,NULL,'1982-02-00','http://en.wikipedia.org/wiki/The_smiths');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (337,'The used',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/The_used');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (338,'Usher',NULL,17,'1991-02-00','http://en.wikipedia.org/wiki/Usher_(entertainer)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (342,'Bob Dylan',NULL,29,'1961-02-00','http://en.wikipedia.org/wiki/Bob_Dylan');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (345,'Fleetwood Mac',NULL,NULL,'1967-02-00','http://en.wikipedia.org/wiki/Fleetwood_Mac');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (348,'King Crimson',NULL,NULL,'1969-02-00','http://en.wikipedia.org/wiki/King_Crimson');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (350,'Moby',NULL,88,'1982-02-00','http://en.wikipedia.org/wiki/Moby');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (351,'Neil Young',NULL,78,'1960-02-00','http://en.wikipedia.org/wiki/Neil_Young');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (354,'Angra',NULL,30,'1991-02-00','http://en.wikipedia.org/wiki/Angra_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (356,'Blink-182',NULL,NULL,'1992-02-00','http://en.wikipedia.org/wiki/Blink-182');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (357,'Bob Marley',NULL,NULL,'1962-02-00','http://en.wikipedia.org/wiki/Bob_Marley');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (358,'Chico Buarque',NULL,27,'1962-02-00','http://en.wikipedia.org/wiki/Chico_Buarque');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (359,'Hans Zimmer',NULL,NULL,'1977-02-00','http://en.wikipedia.org/wiki/Hans_Zimmer');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (360,'Korpiklaani',NULL,NULL,'1993-02-00','http://en.wikipedia.org/wiki/Korpiklaani');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (363,'Pixies',NULL,74,'1986-02-00','http://en.wikipedia.org/wiki/Pixies');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (364,'Tuatha de Danann',NULL,51,'1995-02-00','http://en.wikipedia.org/wiki/Tuatha_de_Danann_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (365,'Chris Brown',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Chris_Brown');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (366,'David Guetta',NULL,NULL,'1984-02-00','http://en.wikipedia.org/wiki/David_Guetta');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (367,'Enrique Iglesias',NULL,34,'1994-02-00','http://en.wikipedia.org/wiki/Enrique_Iglesias');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (368,'Tramar Dillard',NULL,NULL,'2006-02-00','http://en.wikipedia.org/wiki/Flo_Rida');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (371,'Jota Quest',NULL,3,'1996-02-00','http://en.wikipedia.org/wiki/Jota_Quest');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (374,'Ne-yo',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Ne-yo');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (376,'Pitbull',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Pitbull_(rapper)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (379,'Ylvis',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Ylvis');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (380,'A-ha',NULL,1,'1982-02-00','http://en.wikipedia.org/wiki/A-ha');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (382,'Dire Straits',NULL,NULL,'1977-02-00','http://en.wikipedia.org/wiki/Dire_Straits');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (383,'Ghost BC',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Ghost_BC');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (385,'MC Daleste',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/MC_Daleste');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (387,'Oficina G3',NULL,NULL,'1987-02-00','http://en.wikipedia.org/wiki/Oficina_G3');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (390,'Chiclete Com Banana',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Chiclete_com_banana');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (393,'Ørjan Nilsen',NULL,NULL,'2004-02-00','http://en.wikipedia.org/wiki/%C3%98rjan_Nilsen');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (394,'Above & Beyond',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Above_%26_Beyond_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (396,'Alex M.O.R.P.H.',NULL,NULL,'2003-02-00','http://en.wikipedia.org/wiki/Alex_M.O.R.P.H.');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (397,'Aly & Fila',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Aly_%26_Fila');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (398,'Andrew Rayel',NULL,NULL,'2005-02-00','http://en.wikipedia.org/wiki/Andrew_Rayel');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (399,'Andy Moor',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Andy_Moor_(DJ)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (401,'Arty',NULL,NULL,'2009-02-00','http://en.wikipedia.org/wiki/Arty_(musician)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (406,'Dash Berlin',NULL,33,'2007-02-00','http://en.wikipedia.org/wiki/Dash_Berlin');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (409,'Eagles',NULL,NULL,'1971-02-00','http://en.wikipedia.org/wiki/Eagles_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (410,'Electric Light Orchestra',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Electric_light_orchestra');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (413,'Ferry Corsten',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Ferry_corsten');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (415,'Giuseppe Ottaviani',NULL,NULL,'1999-02-00','http://en.wikipedia.org/wiki/Giuseppe_Ottaviani');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (419,'John O\'Callaghan',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/John_O%27Callaghan_(musician)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (420,'John Williams',NULL,158,'1952-02-00','http://en.wikipedia.org/wiki/John_williams');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (421,'Jorn van Deynhoven',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Jorn_van_Deynhoven');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (422,'Journey',NULL,105,'1973-02-00','http://en.wikipedia.org/wiki/Journey_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (425,'Markus Schulz',NULL,135,'1990-02-00','http://en.wikipedia.org/wiki/Markus_Schulz');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (427,'NERVO',NULL,25,'2005-02-00','http://en.wikipedia.org/wiki/Nervo_(duo)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (430,'OceanLab',NULL,10,'2000-02-00','http://en.wikipedia.org/wiki/OceanLab');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (431,'Paul van Dyk',NULL,NULL,'1991-02-00','http://en.wikipedia.org/wiki/Paul_van_Dyk');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (437,'Sander van Doorn',NULL,NULL,'2004-02-00','http://en.wikipedia.org/wiki/Sander_van_Doorn');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (438,'Simon Patterson',NULL,23,'2000-02-00','http://en.wikipedia.org/wiki/Simon_Patterson_(musician)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (439,'Supertramp',NULL,NULL,'1969-02-00','http://en.wikipedia.org/wiki/Supertramp');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (442,'The Trammps',NULL,67,'1972-02-00','http://en.wikipedia.org/wiki/The_Trammps');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (443,'The Who',NULL,10,'1964-02-00','http://en.wikipedia.org/wiki/The_Who');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (444,'Tiesto',NULL,NULL,'1994-02-00','http://en.wikipedia.org/wiki/Ti%C3%ABsto');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (445,'Tim Maia',NULL,27,'1956-02-00','http://en.wikipedia.org/wiki/Tim_Maia');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (446,'Ummet Ozcan',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Ummet_Ozcan');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (447,'W&W',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/W%26W');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (449,'ZZ Top',NULL,26,'1969-02-00','http://en.wikipedia.org/wiki/Zz_top');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (451,'Yusuf Islam',NULL,NULL,'1966-02-00','http://en.wikipedia.org/wiki/Cat_Stevens');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (458,'Megadeth',NULL,15,'1983-02-00','http://en.wikipedia.org/wiki/Megadeth');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (459,'System of a Down',NULL,NULL,'1994-02-00','http://en.wikipedia.org/wiki/System_of_a_Down');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (460,'É o Tchan',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/%C3%89_o_Tchan!');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (461,'30 Seconds to Mars',NULL,15,'1998-02-00','http://en.wikipedia.org/wiki/30_Seconds_to_Mars');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (468,'Beyonce',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Beyonce');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (469,'Black Keys',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Black_keys');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (470,'Bombay Bicycle Club',NULL,80,'2005-02-00','http://en.wikipedia.org/wiki/Bombay_Bicycle_Club');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (472,'Canon Blue',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Canon_Blue');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (473,'Cansei de ser sexy',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Cansei_de_ser_sexy');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (476,'Ellie Goulding',NULL,NULL,'2007-02-00','http://en.wikipedia.org/wiki/Ellie_Goulding');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (479,'Foals',NULL,NULL,'2005-02-00','http://en.wikipedia.org/wiki/Foals');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (483,'Katy Perry',NULL,NULL,'1999-02-00','http://en.wikipedia.org/wiki/Katy_Perry');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (487,'Michael Joseph Jackson',NULL,NULL,'1964-02-00','http://en.wikipedia.org/wiki/Michael_Jackson');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (493,'Sandy e Junior',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Sandy_e_Junior');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (498,'The xx',NULL,NULL,'2005-02-00','http://en.wikipedia.org/wiki/The_xx');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (499,'Two Door Cinema Club',NULL,151,'2007-02-00','http://en.wikipedia.org/wiki/Two_Door_Cinema_Club');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (500,'Vampire Weekend',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Vampire_Weekend');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (501,'Albert Hammond, Jr.',NULL,NULL,'1999-02-00','http://en.wikipedia.org/wiki/Albert_Hammond,_Jr.');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (502,'Alt J',NULL,49,'2007-02-00','http://en.wikipedia.org/wiki/Alt-J');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (505,'Babyshambles',NULL,10,'2003-02-00','http://en.wikipedia.org/wiki/Babyshambles');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (506,'Best Coast',NULL,NULL,'2009-02-00','http://en.wikipedia.org/wiki/Best_Coast');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (507,'Bjork',NULL,NULL,'1977-02-00','http://en.wikipedia.org/wiki/Bj%C3%B6rk');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (509,'Bon Iver',NULL,112,'2007-02-00','http://en.wikipedia.org/wiki/Bon_Iver');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (510,'Breakbot',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Breakbot');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (511,'CSS',NULL,30,'2003-02-00','http://en.wikipedia.org/wiki/CSS_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (512,'Cage the Elephant',NULL,143,'2006-02-00','http://en.wikipedia.org/wiki/Cage_the_Elephant');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (513,'Cake',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Cake');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (514,'Carissa\'s Wierd',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Carissa%27s_Wierd');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (515,'Courteeners',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Courteeners');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (517,'Cults',NULL,NULL,'2010-02-00','http://en.wikipedia.org/wiki/Cults_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (519,'Delta Spirit',NULL,NULL,'2005-02-00','http://en.wikipedia.org/wiki/Delta_Spirit');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (520,'DetektivbyrÃ¥n',NULL,13,'2005-02-00','http://en.wikipedia.org/wiki/Detektivbyr%C3%A5n');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (524,'Franz Ferdinand',NULL,75,'2002-02-00','http://en.wikipedia.org/wiki/Franz_Ferdinand_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (526,'Haim',NULL,15,'2006-02-00','http://en.wikipedia.org/wiki/Haim_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (527,'Interpol',NULL,NULL,'1997-02-00','http://en.wikipedia.org/wiki/Interpol_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (528,'Jake Bugg',NULL,NULL,'2011-02-00','http://en.wikipedia.org/wiki/Jake_Bugg');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (529,'Julian Casablancas',NULL,NULL,'1998-02-00','http://en.wikipedia.org/wiki/Julian_Casablancas');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (530,'Justice',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Justice');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (531,'Justin Bieber',NULL,77,'2008-02-00','http://en.wikipedia.org/wiki/Justin_Bieber');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (532,'Kaiser Chiefs',NULL,49,'1996-02-00','http://en.wikipedia.org/wiki/Kaiser_Chiefs');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (533,'Kakkmaddafakka',NULL,14,'2004-02-00','http://en.wikipedia.org/wiki/Kakkmaddafakka');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (534,'Kasabian',NULL,NULL,'1997-02-00','http://en.wikipedia.org/wiki/Kasabian');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (535,'Kid Cudi',NULL,20,'2003-02-00','http://en.wikipedia.org/wiki/Kid_Cudi');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (536,'Kings of Convenience',NULL,14,'1999-02-00','http://en.wikipedia.org/wiki/Kings_of_Convenience');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (538,'Little Joy',NULL,15,'2007-02-00','http://en.wikipedia.org/wiki/Little_Joy');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (539,'Locksley',NULL,NULL,'2003-02-00','http://en.wikipedia.org/wiki/Locksley_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (541,'M83',NULL,68,'2001-02-00','http://en.wikipedia.org/wiki/M83_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (542,'MGMT',NULL,63,'2004-02-00','http://en.wikipedia.org/wiki/MGMT');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (545,'Neutral Milk Hotel',NULL,71,'1989-02-00','http://en.wikipedia.org/wiki/Neutral_Milk_Hotel');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (546,'Of Monsters and Men',NULL,41,'2010-02-00','http://en.wikipedia.org/wiki/Of_Monsters_and_Men');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (547,'One Direction',NULL,NULL,'2010-02-00','http://en.wikipedia.org/wiki/One_Direction');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (548,'Passion Pit',NULL,120,'2007-02-00','http://en.wikipedia.org/wiki/Passion_Pit');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (551,'Racounters',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Raconteurs');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (553,'Rebbeca Black',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Rebbeca_Black');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (558,'The Cribs',NULL,160,'2002-02-00','http://en.wikipedia.org/wiki/The_Cribs');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (559,'The Enemy',NULL,NULL,'2006-02-00','http://en.wikipedia.org/wiki/The_Enemy_(UK_band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (560,'The Films',NULL,NULL,'2007-02-00','http://en.wikipedia.org/wiki/The_Films_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (561,'The Flaming Lips',NULL,9,'1983-02-00','http://en.wikipedia.org/wiki/The_Flaming_Lips');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (562,'The Fratellis',NULL,75,'2005-02-00','http://en.wikipedia.org/wiki/The_Fratellis');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (564,'The Kills',NULL,NULL,'2000-02-00','http://en.wikipedia.org/wiki/The_Kills');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (566,'The Last Shadow Puppets',NULL,NULL,'2007-02-00','http://en.wikipedia.org/wiki/The_Last_Shadow_Puppets');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (568,'The Paddingtons',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/The_Paddingtons');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (569,'The Pixies',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/The_Pixies');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (570,'The Royal Concept',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/The_Royal_Concept');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (571,'The Royalty',NULL,NULL,'2005-02-00','http://en.wikipedia.org/wiki/The_Royalty');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (572,'The Soft Pack',NULL,43,'2007-02-00','http://en.wikipedia.org/wiki/The_Soft_Pack');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (574,'The Vaccines',NULL,NULL,'2010-02-00','http://en.wikipedia.org/wiki/The_Vaccines');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (575,'The View',NULL,104,'2005-02-00','http://en.wikipedia.org/wiki/The_View_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (576,'The Virgins',NULL,NULL,'2005-02-00','http://en.wikipedia.org/wiki/The_Virgins');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (577,'The libertines',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/The_libertines');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (580,'Weezer',NULL,15,'1992-02-00','http://en.wikipedia.org/wiki/Weezer');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (581,'White Lies',NULL,109,'2007-02-00','http://en.wikipedia.org/wiki/White_Lies_(band)');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (586,'Fratellis',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Fratellis');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (587,'Macklemore',NULL,NULL,'1999-02-00','http://en.wikipedia.org/wiki/Macklemore');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (588,'Men at Work',NULL,25,'1979-02-00','http://en.wikipedia.org/wiki/Men_at_Work');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (595,'Charlie Parker',NULL,NULL,'1937-02-00','http://en.wikipedia.org/wiki/Charlie_Parker');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (596,'Chet Baker',NULL,NULL,'1949-02-00','http://en.wikipedia.org/wiki/Chet_Baker');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (598,'David Matthews',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/David_Matthews_Band');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (607,'John Coltrane',NULL,NULL,'1946-02-00','http://en.wikipedia.org/wiki/John_Coltrane');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (609,'Johnny Cash',NULL,NULL,'1954-02-00','http://en.wikipedia.org/wiki/Johnny_Cash');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (622,'Ray Charles',NULL,130,'1947-02-00','http://en.wikipedia.org/wiki/Ray_Charles');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (626,'Simon and Garfunkel',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Simon_and_Garfunkel');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (627,'The Animals',NULL,NULL,'1963-02-00','http://en.wikipedia.org/wiki/The_Animals');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (628,'The Cure',NULL,NULL,'1976-02-00','http://en.wikipedia.org/wiki/The_Cure');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (631,'The Mamas the papas',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/The_Mamas_%26_the_Papas');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (641,'Snow Patrol',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/Snow_patrol');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (646,'AC/DC',NULL,NULL,NULL,'http://en.wikipedia.org/wiki/AC_DC');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (654,'Avenged Sevenfold',NULL,NULL,'1999-02-00','http://en.wikipedia.org/wiki/Avenged_Sevenfold');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (657,'Guns N\' Roses',NULL,NULL,'1985-02-00','http://en.wikipedia.org/wiki/Guns_N\'_Roses');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (664,'Rammstein',NULL,NULL,'1994-02-00','http://en.wikipedia.org/wiki/Rammstein');
INSERT INTO `MusicalArtist` (`id`,`artistic_name`,`genre_id`,`city_id`,`creation_date`,`wiki_address`) VALUES (665,'Scorpions',NULL,48,'1965-02-00','http://en.wikipedia.org/wiki/Scorpions_(band)');
