INSERT INTO Person (login,name,hometown) VALUES ('eduardapodesta','eduarda viana podesta','');
INSERT INTO Person (login,name,hometown) VALUES ('ivancerboncini','ivan de campos cerboncini','');
INSERT INTO Person (login,name,hometown) VALUES ('felipehiga','felipe kenji higa','');
INSERT INTO Person (login,name,hometown) VALUES ('fernandothiers','fernando barbosa thiers','');
INSERT INTO Person (login,name,hometown) VALUES ('erikaalbizzati','erika couto albizzati','');
INSERT INTO Person (login,name,hometown) VALUES ('thiagobalbo','thiago duarte balbo','');
INSERT INTO Person (login,name,hometown) VALUES ('danielferreira','daniel breves ferreira','');
INSERT INTO Person (login,name,hometown) VALUES ('ramonmaciel','ramon carvalho maciel','');
INSERT INTO Person (login,name,hometown) VALUES ('tiagoferreira','tiago de lima ferreira','');
INSERT INTO Person (login,name,hometown) VALUES ('rafaelxavier','rafael xavier','');
INSERT INTO Person (login,name,hometown) VALUES ('nicholasmizoguchi','nicholas matuzita mizoguchi','');
INSERT INTO Person (login,name,hometown) VALUES ('tuliosilva','tulio bazan da silva','');
INSERT INTO Person (login,name,hometown) VALUES ('leonnardorabello','leonnardo chagas rabello','');
INSERT INTO Person (login,name,hometown) VALUES ('lukaslopes','lukas antunes lopes','');
INSERT INTO Person (login,name,hometown) VALUES ('rafaelgarcia','rafael matheus garcia','');
INSERT INTO Person (login,name,hometown) VALUES ('joaodalben','joao henrique dalben','');
INSERT INTO Person (login,name,hometown) VALUES ('caioteixeira','caio teixeira','');
INSERT INTO Person (login,name,hometown) VALUES ('elisadellarriva','elisa dellarriva','');
INSERT INTO Person (login,name,hometown) VALUES ('fernandogoncalves','fernando henrique dos santos goncalves','');
INSERT INTO Person (login,name,hometown) VALUES ('luanbicesto','luan gustavo bicesto','');
INSERT INTO Person (login,name,hometown) VALUES ('lucianosabenca','luciano padua sabenca','');
INSERT INTO Person (login,name,hometown) VALUES ('pedroalmeida','pedro cordeiro de almeida','');
INSERT INTO Person (login,name,hometown) VALUES ('tomasqueiroga','tomas silva queiroga','');
INSERT INTO Person (login,name,hometown) VALUES ('fabiolira','fabio maffei lira','');
INSERT INTO Person (login,name,hometown) VALUES ('guilhermemendes','guilherme da rocha alves mendes','');
INSERT INTO Person (login,name,hometown) VALUES ('guilhermemazzariol','guilherme sbrolini mazzariol','');
INSERT INTO Person (login,name,hometown) VALUES ('raphaelfranco','raphael marques franco','');
INSERT INTO Person (login,name,hometown) VALUES ('willianszati','willians hidalgo zati','');
INSERT INTO Person (login,name,hometown) VALUES ('victortavares','victor guilherme oliveira semedo tavares','');
INSERT INTO Person (login,name,hometown) VALUES ('fernandohoyo','fernando luiz del hoyo','campinas');
INSERT INTO Person (login,name,hometown) VALUES ('lucasmello','lucas de campos mello','');
INSERT INTO Person (login,name,hometown) VALUES ('wilsonneto','wilson jose prata neto','');
INSERT INTO Person (login,name,hometown) VALUES ('andreiauratsuka','andreia yukie uratsuka','');
INSERT INTO Person (login,name,hometown) VALUES ('victorsilva','victor akira hassuda silva','');
INSERT INTO Person (login,name,hometown) VALUES ('leonardosilva','leonardo de oliveira silva','');
INSERT INTO Person (login,name,hometown) VALUES ('gabrielbezerra','gabriel massaki wakano bezerra','');
INSERT INTO Person (login,name,hometown) VALUES ('elvisrabello','elvis rabello','');
INSERT INTO Person (login,name,hometown) VALUES ('caiopalissari','caio vinicius uvini palissari','');
INSERT INTO Person (login,name,hometown) VALUES ('cibellebegalli','cibelle begalli','');
INSERT INTO Person (login,name,hometown) VALUES ('diegorocha','diego rocha','');
INSERT INTO Person (login,name,hometown) VALUES ('fellipecaetano','fellipe santiago scarpa caetano','');
INSERT INTO Person (login,name,hometown) VALUES ('gustavonunes','gustavo cesar nunes','');
INSERT INTO Person (login,name,hometown) VALUES ('juceliofonseca','jucelio evangelista fonseca','');
INSERT INTO Person (login,name,hometown) VALUES ('murilocruz','murilo de lima cruz','');
INSERT INTO Person (login,name,hometown) VALUES ('felipecaminada','felipe caminada','');
INSERT INTO Person (login,name,hometown) VALUES ('lucasbatista','lucas oliveira batista','');
INSERT INTO Person (login,name,hometown) VALUES ('andresantanche','andre santanche','');
INSERT INTO Person (login,name,hometown) VALUES ('luizgomes','Luiz Celso Gomes Jr','');
INSERT INTO Person (login,name,hometown) VALUES ('lucaslima','Lucas Domingues Lima','Campinas');
INSERT INTO Person (login,name,hometown) VALUES ('viniciussantos','Vinicius Pereira dos Santos','Campinas');